package zipstream

import "archive/zip"

const (
	localFileHeaderLength     = 30
	centralFileHeaderLength   = 46
	endOfCentralDirRecordSize = 22
	zipUint32Max              = 1<<32 - 1
)

// ArchiveSizeFiltered returns the exact byte length of the archive generated by
// WriteFiltered, if it can be represented without zip64 metadata.
func ArchiveSizeFiltered(files []*zip.File, keep Predicate) (int64, bool) {
	var localTotal int64
	var centralTotal int64
	var count int

	for _, file := range files {
		if !keep(file) {
			continue
		}
		header := RewriteRawHeader(&file.FileHeader)

		if header.CompressedSize64 >= zipUint32Max ||
			// file is too large for zip64, so we can't
			// calculate the size without zip64 metadata
			header.UncompressedSize64 >= zipUint32Max {
			return 0, false
		}

		nameLength := int64(len(header.Name))
		commentLength := int64(len(header.Comment))

		localTotal += localFileHeaderLength +
			nameLength +
			int64(header.CompressedSize64)

		centralTotal += centralFileHeaderLength +
			nameLength +
			commentLength

		count++
	}

	if count >= 0xffff ||
		localTotal >= zipUint32Max ||
		centralTotal >= zipUint32Max {
		return 0, false
	}

	return localTotal + centralTotal + endOfCentralDirRecordSize, true
}
